# Form implementation generated from reading ui file 'ui/category_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(50, 50, 256, 192))
        self.tableView.setObjectName("tableView")
        self.tableView.setColumnCount(3)
        self.tableView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableView.setHorizontalHeaderItem(2, item)
        self.btn_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(50, 270, 56, 17))
        self.btn_add.setObjectName("btn_add")
        self.btn_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(140, 270, 56, 17))
        self.btn_edit.setObjectName("btn_edit")
        self.btn_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(250, 270, 56, 17))
        self.btn_delete.setObjectName("btn_delete")
        self.nameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(330, 60, 113, 20))
        self.nameInput.setObjectName("nameInput")
        self.descriptionInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.descriptionInput.setGeometry(QtCore.QRect(330, 100, 113, 20))
        self.descriptionInput.setObjectName("descriptionInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableView.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableView.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Danh Mục"))
        item = self.tableView.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mô tả"))
        self.btn_add.setText(_translate("MainWindow", "Add"))
        self.btn_edit.setText(_translate("MainWindow", "Edit"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
